# Generated by Django 3.1.2 on 2020-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_questionnaire_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='lang',
            field=models.CharField(choices=[('C', 'C++'), ('P', 'Python'), ('J', 'Java')], default='C', max_length=1),
        ),
    ]
