# Generated by Django 3.1.2 on 2020-12-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_solution_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedquestion', to='competition.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.TextField(default=None)),
                ('output1', models.TextField(default=None)),
                ('input2', models.TextField(default=None)),
                ('output2', models.TextField(default=None)),
                ('input3', models.TextField(default=None)),
                ('output3', models.TextField(default=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedq', to='competition.questionnaire')),
            ],
        ),
    ]
