# Generated by Django 3.1.2 on 2020-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_correctsolution_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_Correct',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
