# Generated by Django 3.1.2 on 2020-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_solution_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='is_Correct',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
