# Generated by Django 3.1.2 on 2020-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20201205_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctsolution',
            name='input1',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='correctsolution',
            name='input2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='correctsolution',
            name='input3',
            field=models.TextField(default=None, null=True),
        ),
    ]
